version: '3'
services:
  # Dockerfileを移動したのでちょっと修正する必要あり
  rails:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  # ここにdiscord_botのビルドを書く
  discord_bot:
    build:  
    volumes:
      - .:/
    ports:
      - ""
