version: '3'
services:
  rails:
    build: ./docker/rails
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  discord_bot:
    build: ./docker/discord_bot
    volumes:
      - .:/app
    tty: true
    stdin_open: true
